### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by phlipper** [renocollective/member-portal#83]
Document the process required for contributing to this project, both in technical terms and process terms. 

- [ ] Add a [`CONTRIBUTING.md` file](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
- [ ] Add a [Pull Request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

**Comment by suetingc** [comment]
notes: 

issues template
- As a super user, (as a what)
- I would like to send an invite to new members, (what do you want to do)
- so that they can register and be displayed in the member directory. (why do you need this to happen?)

pull request template
- Decide whether to store your pull request template in your repository's root, docs, or .github directory.

**Comment by BrendaPenn** [comment]
Closed with PR #149
